name: LAPRAS-Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-card:
    name: LAPRAS-Card
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: 'https://lapras.com/public/Symthy'
          ICON_FIRST: '#030E21'
          ICON_SECOND: '#90b2c1'
          BACKGROUND_FIRST: '#020E27'
          BACKGROUND_SECOND: '#3190e3'
          LANG: 'ja'
          # https://lapras-card-generator.vercel.app でカスタマイズしたデザインを設定可能

